ao-bringup: Improve EasyMini turnon and test scripts
Wait less time before trying the test script.
Have the test script wait for the device to appear. And then use
colors to help make the results clear.

Signed-off-by: Keith Packard <keithp@keithp.com>

diff --git a/ao-bringup/test-easymini b/ao-bringup/test-easymini
--- a/ao-bringup/test-easymini
+++ b/ao-bringup/test-easymini
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 VERSION=1.0
 PRODUCT=EasyMini
@@ -8,48 +8,55 @@ echo "$PRODUCT-v$VERSION Test Program"
 echo "Copyright 2014 by Keith Packard.  Released under GPL v2"
 echo
 echo "Expectations:"
-echo "\t$PRODUCT v$VERSION powered from USB"
+echo -e "\t$PRODUCT v$VERSION powered from USB"
 echo
 
-ret=1
-ao-list | while read product serial dev; do
-    case "$product" in
-	"$PRODUCT-v$VERSION")
+found=0
+while [ $found -eq 0 ]; do
+    (ao-list; echo END END END END) | while read product serial dev; do
+	case "$product" in
+	    "$PRODUCT-v$VERSION")
 
-	    echo "Testing $product $serial $dev"
-	    echo ""
-	    
-	    ./test-igniters "$dev" drogue main
-	    echo ""
+		found=1
+		echo -e '\e[34m'Testing $product $serial $dev'\e[39m'
+		echo ""
+		
+		./test-igniters "$dev" drogue main
+		echo ""
 
-	    echo "Testing baro sensor"
-	    ../ao-tools/ao-test-baro/ao-test-baro --tty="$dev"
+		echo "Testing baro sensor"
+		../ao-tools/ao-test-baro/ao-test-baro --tty="$dev"
 
-	    case $? in
-		0)
-		    ;;
-		*)
-		    echo "failed"
+		if [ $? -ne 0 ]; then
+		    echo -e '\e[31m'"$PRODUCT-$VERSION serial $serial failed"'\e[39m'
 		    exit 1
-	    esac
-	    echo""
+		fi
+		echo""
 
-	    FLASHSIZE=1048576
+		FLASHSIZE=1048576
 
-	    echo "Testing flash"
-	    ../ao-tools/ao-test-flash/ao-test-flash --tty="$dev" "$FLASHSIZE"
+		echo "Testing flash"
+		../ao-tools/ao-test-flash/ao-test-flash --tty="$dev" "$FLASHSIZE"
 
-	    case $? in
-		0)
-		    ;;
-		*)
-		    echo "failed"
+		if [ $? -ne 0 ]; then
+		    echo -e '\e[31m'"$PRODUCT-$VERSION serial $serial failed"'\e[39m'
 		    exit 1
-	    esac
-	    echo""
+		fi
 
-	    echo "$PRODUCT-v$VERSION" serial "$serial" is ready to ship
-	    ret=0
-	    ;;
-    esac
+		echo ""
+
+		echo -e '\e[32m'"$PRODUCT-v$VERSION" serial "$serial" is ready to ship'\e[39m'
+		exit 0
+		;;
+	    END)
+		exit 2
+		;;
+	esac
+    done
+    result=$?
+    if [ $result -ne 2 ]; then
+	exit $result
+    fi
+    echo 'No device, sleeping...'
+    sleep 1
 done
