ao-bringup: Improve igniter testing. Add TeleMega and TeleMetrum testing.
The script lets you re-try each one when they fail, which is nice if
you're hand-holding the setup.

The TeleMetrum and TeleMega tests are adapted from the EasyMega tests
and are hooked up to the turnon scripts.

Signed-off-by: Keith Packard <keithp@keithp.com>

diff --git a/ao-bringup/test-telemega b/ao-bringup/test-telemega
--- a/ao-bringup/test-telemega
+++ b/ao-bringup/test-telemega
@@ -1,7 +1,7 @@
 #!/bin/sh
 
-VERSION=1.0
-PRODUCT=EasyMega
+VERSION=0.1
+PRODUCT=TeleMega
 BASE=`echo $PRODUCT | tr 'A-Z' 'a-z'`
 
 echo "$PRODUCT-v$VERSION Test Program"
@@ -17,7 +17,6 @@ ao-list | while read product serial dev; do
 	"$PRODUCT-v$VERSION")
 
 	    echo "Testing $product $serial $dev"
-	    echo ""
 
 	    ./test-igniters $dev drogue main 0 1 2 3
 	    echo""
@@ -38,6 +37,18 @@ ao-list | while read product serial dev; do
 
 	    echo "Testing flash"
 	    ../ao-tools/ao-test-flash/ao-test-flash --tty="$dev" "$FLASHSIZE"
+
+	    case $? in
+		0)
+		    ;;
+		*)
+		    echo "failed"
+		    exit 1
+	    esac
+	    echo""
+
+	    echo "Testing GPS"
+	    ../ao-tools/ao-test-gps/ao-test-gps --tty="$dev"
 
 	    case $? in
 		0)
diff --git a/ao-bringup/test-telemetrum b/ao-bringup/test-telemetrum
--- a/ao-bringup/test-telemetrum
+++ b/ao-bringup/test-telemetrum
@@ -1,7 +1,7 @@
 #!/bin/sh
 
-VERSION=1.0
-PRODUCT=EasyMega
+VERSION=2.0
+PRODUCT=TeleMetrum
 BASE=`echo $PRODUCT | tr 'A-Z' 'a-z'`
 
 echo "$PRODUCT-v$VERSION Test Program"
@@ -19,8 +19,8 @@ ao-list | while read product serial dev; do
 	    echo "Testing $product $serial $dev"
 	    echo ""
 
-	    ./test-igniters $dev drogue main 0 1 2 3
-	    echo""
+	    ./test-igniters "$dev" drogue main
+	    echo ""
 
 	    echo "Testing baro sensor"
 	    ../ao-tools/ao-test-baro/ao-test-baro --tty="$dev"
@@ -38,6 +38,18 @@ ao-list | while read product serial dev; do
 
 	    echo "Testing flash"
 	    ../ao-tools/ao-test-flash/ao-test-flash --tty="$dev" "$FLASHSIZE"
+
+	    case $? in
+		0)
+		    ;;
+		*)
+		    echo "failed"
+		    exit 1
+	    esac
+	    echo""
+
+	    echo "Testing GPS"
+	    ../ao-tools/ao-test-gps/ao-test-gps --tty="$dev"
 
 	    case $? in
 		0)
