first cut at turnon scripts for EasyTimer v2

diff --git a/ao-bringup/turnon_easytimer_v1 b/ao-bringup/turnon_easytimer_v1
--- a/ao-bringup/turnon_easytimer_v1
+++ b/ao-bringup/turnon_easytimer_v1
@@ -1,7 +1,11 @@
 #!/bin/sh
 
-# EasyTimer v2 all arrive from the assembler with 
-# the bootloader already flashed. 
+if [ -x /usr/bin/ao-flash-stm ]; then
+	FLASH_STM=/usr/bin/ao-flash-stm
+else
+	echo "Can't find ao-flash-stm!  Aborting."
+	exit 1
+fi
 
 if [ -x /usr/bin/ao-usbload ]; then
 	USBLOAD=/usr/bin/ao-usbload
@@ -10,15 +14,16 @@ else
 	exit 1
 fi
 
-VERSION=2
+VERSION=1
 REPO=~/altusmetrumllc/Binaries
 PRODUCT=EasyTimer
 
 echo "$PRODUCT v$VERSION Turn-On and Calibration Program"
-echo "Copyright 2024 by Bdale Garbee.  Released under GPL v3"
+echo "Copyright 2020 by Bdale Garbee.  Released under GPL v3"
 echo
 echo "Expectations:"
 echo "\t$PRODUCT v$VERSION powered from USB"
+echo "\t\twith ST-Link-V2 cabled to debug header"
 echo
 
 case $# in
@@ -35,6 +40,12 @@ case $# in
 	exit 1;
 	;;
 esac
+
+echo $FLASH_STM
+
+$FLASH_STM $REPO/loaders/easytimer-v$VERSION*.elf 
+
+sleep 3
 
 $USBLOAD --serial=$SERIAL --force $REPO/easytimer-v$VERSION*.elf || exit 1
 
@@ -62,6 +73,6 @@ done
 
 echo 'E 1' > $dev
 
-./test-easytimer-v2
+./test-easytimer
 
 exit $?
