ao-bringup: Revert EasyMini scripts to 1.0
Signed-off-by: Keith Packard <keithp@keithp.com>

diff --git a/ao-bringup/turnon_easymini b/ao-bringup/turnon_easymini
--- a/ao-bringup/turnon_easymini
+++ b/ao-bringup/turnon_easymini
@@ -1,10 +1,12 @@
 #!/bin/sh
 
-if [ -x /usr/bin/dfu-util ]; then
-    DFU_UTIL=/usr/bin/dfu-util
+if [ -x ../ao-tools/ao-flash/ao-flash-lpc ]; then
+	FLASH_LPC=../ao-tools/ao-flash/ao-flash-lpc
+elif [ -x /usr/bin/ao-flash-lpc ]; then
+	FLASH_LPC=/usr/bin/ao-flash-lpc
 else
-    echo "Can't find dfu-util! Aborting."
-    exit 1
+	echo "Can't find ao-flash-lpc!  Aborting."
+	exit 1
 fi
 
 if [ -x ../ao-tools/ao-usbload/ao-usbload ]; then
@@ -16,16 +18,17 @@ else
 	exit 1
 fi
 
-VERSION=2.0
+VERSION=1.0
 PRODUCT=EasyMini
 BASE=`echo $PRODUCT | tr 'A-Z' 'a-z'`
 echo $FILE
 
 echo "$PRODUCT v$VERSION Turn-On and Calibration Program"
-echo "Copyright 2010 by Bdale Garbee.  Released under GPL v2+"
+echo "Copyright 2010 by Bdale Garbee.  Released under GPL v2"
 echo
 echo "Expectations:"
-echo "\t$PRODUCT v$VERSION powered and connected to USB"
+echo "\t$PRODUCT v$VERSION powered from USB"
+echo "\t\twith ST-Link-V2 cabled to debug header"
 echo
 
 case $# in
@@ -46,19 +49,17 @@ esac
 #
 # Use released versions of everything
 #
-FLASH_FILE=~/altusmetrumllc/Binaries/loaders/easymini-v2.0-altos-flash-*.bin
-ALTOS_FILE=~/altusmetrumllc/Binaries/easymini-v2.0-*.elf
+FLASH_FILE=~/altusmetrumllc/Binaries/loaders/easymini-v1.0-altos-flash-*.elf
+ALTOS_FILE=~/altusmetrumllc/Binaries/easymini-v1.0-*.elf
 
 #FLASH_FILE=../src/$BASE-v$VERSION/flash-loader/$BASE-v$VERSION-altos-flash-*.elf
 #ALTOS_FILE=../src/$BASE-v$VERSION/*.ihx
 
-if lsusb -d 0483:df11 | grep -q STM; then
-    echo $DFU_UTIL -v -v -R -a 0 -s 0x08000000:leave -D $FLASH_FILE
+echo $FLASH_LPC $FLASH_FILE
 
-    $DFU_UTIL -a 0 -s 0x08000000:leave -D $FLASH_FILE
+$FLASH_LPC $FLASH_FILE || exit 1
 
-    sleep 2
-fi
+sleep 1
 
 echo $USBLOAD $ALTOS_FILE
 
@@ -66,6 +67,6 @@ $USBLOAD --serial=$SERIAL $ALTOS_FILE || exit 1
 
 sleep 1
 
-./test-easymini
+./test-easymini-v1.0
 
 exit $?
